# Generated by Django 4.2.13 on 2024-09-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_artist_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='otp',
            field=models.CharField(default='00000', max_length=5, verbose_name='OTP'),
        ),
        migrations.AddField(
            model_name='artist',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
