# Generated by Django 4.2.13 on 2024-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
